# Generated by Django 6.0.4 on 2026-04-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bunq_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
