# Generated by Django 6.0.4 on 2026-04-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_bunq_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bunq_context',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
