# Generated by Django 6.0.4 on 2026-04-25 02:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_bunq_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('iban', models.CharField(max_length=34)),
                ('bunq_user_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'nickname')},
            },
        ),
        migrations.CreateModel(
            name='SalarySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_description', models.TextField(help_text='Original natural-language allocation instructions from the user.')),
                ('trigger_keyword', models.CharField(help_text="Counterparty name to match (e.g. 'ASML').", max_length=128)),
                ('trigger_min_amount', models.DecimalField(decimal_places=2, help_text='Minimum incoming amount (EUR) to trigger allocation.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_setup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('transfer', 'Transfer to contact'), ('invest', 'Invest via Alpaca'), ('save', 'Move to savings account')], max_length=16)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed EUR amount'), ('percent', 'Percentage of salary')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed EUR amount, or percentage (0–100) depending on amount_type.', max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('invest_symbol', models.CharField(blank=True, help_text="e.g. 'SPY', 'VOO'", max_length=16)),
                ('savings_iban', models.CharField(blank=True, max_length=34)),
                ('description', models.CharField(blank=True, help_text='Human-readable summary of this rule.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order — lower runs first.')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_rules', to='accounts.contact')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.salarysetup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
